# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-amd"
    "asus-wmi"
  ];
  boot.extraModulePackages = [
    pkgs.microcode-amd
    config.boot.kernelPackages.nvidia_x11
  ];
  hardware.graphics.enable = true;
  hardware.nvidia.open = false;
  services = {
    supergfxd = {
      enable = true;
    };
    asusd = {
      enable = true;
      enableUserService = true;
    };
    xserver.videoDrivers = [
      "nvidia"
      "amdgpu"
    ];
  };
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.kernelPackages = pkgs.linuxPackages_latest;
  nixpkgs.config = {
    allowUnfreePredicate =
      pkg:
      builtins.elem (lib.getName pkg) [
        "nvidia-x11"
        "nvidia-settings"
      ];
  };
  environment.systemPackages = [
    pkgs.asusctl
    pkgs.supergfxctl
  ];
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c110a7bb-ef1e-4f7e-9ae0-a1753f71e670";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/EDA9-7336";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
      "defaults"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/a15d9782-ec2e-4ad7-b62d-d619cddadbb9"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
