(require 'dashboard)
(dashboard-setup-startup-hook)
(add-hook 'server-after-make-frame-hook 'dashboard-open)
(require 'evil)
(evil-mode 1)
(require 'which-key)
(which-key-mode)
(setq which-key-side-window-location 'bottom)
(require 'nerd-icons)
